version: '3'
services:
  im:
    container_name: im
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    build: .
    ports:
      - '8081:8080'